apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  namespace: {{ .Release.Namespace }}
data:
  BASE_URL: http://{{ .Release.Name }}-app-service.{{ .Release.Namespace }}.svc.cluster.local:5000
  DB_HOSTNAME: {{ .Release.Name }}-database-service.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.db.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      nodeSelector:
        type: application
      initContainers:
        - name: {{ .Release.Name }}-app-migration
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          command:
            - sh
            - -c
            - flask db upgrade
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-database-config
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secrets
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-app-config
      containers:
        - name: {{ .Release.Name }}-app-container
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-database-config
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secrets
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-app-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
