apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-database-config
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_DATABASE: {{ .Values.db.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-database
  ports:
    - port: {{ .Values.db.port }}
      name: mysql
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-database-service
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      nodeSelector:
        type: database
      containers:
        - name: {{ .Release.Name }}-database-container
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-database-config
            - secretRef:
                name: {{ .Release.Name }}-app-secrets
          volumeMounts:
            - name: {{ .Release.Name }}-database-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-database-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
