apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Release.Name }}-secrets
          serviceAccountRef:
            name: vault-auth-sa

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Release.Name }}-secrets
        property: root_password
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Release.Name }}-secrets
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Release.Name }}-secrets
        property: password
