apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
  namespace: student-api
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: student-app
          serviceAccountRef:
            name: vault-auth-sa

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: school-app-secrets
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: school-app-secrets
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        DATABASE_URI: "mysql+pymysql://{{ .DB_USERNAME }}:{{ .DB_PASSWORD }}@school-database-service.student-api.svc.cluster.local:3306/school"
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: student-app
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: student-app
        property: password
